### ISSUE TITLE
Error when running coordinator demo

### ISSUE THREAD

**Issue by lawlawlaw** [commerceblock/coordinator#17]
Lawrences-MacBook-Pro:coordinator lawrence$ ./scripts/demo.sh && cargo run --example demo
Ocean server stopping
Ocean server starting
Importing challenger key
Issue asset for guardnodes
Create request
[
  "8f571967bb4105eed5dc6d80db6e265026478d299dd4176b9fe17ece854790f9"
]
[
  {
    "genesisBlock": "706f645393a41142e5fc1e1bf6c496bddb26bcada8b9429d4f33a2552eb6e66c",
    "confirmedBlockHeight": 1,
    "startBlockHeight": 5,
    "numTickets": 2,
    "decayConst": 1000,
    "feePercentage": 3,
    "endBlockHeight": 10,
    "startPrice": 50.00000000,
    "auctionPrice": 50.00000000,
    "txid": "5321e588da5c3a074c862c268f728efe764e1498a6d3f280538cc3deb4c26f31"
  }
]
Create request bid
[
  "345bd5c3f0d0d0ddc0a734ffe4838b9f2d401e7281b0b6b64a07c1aa28037955"
]
{
  "genesisBlock": "706f645393a41142e5fc1e1bf6c496bddb26bcada8b9429d4f33a2552eb6e66c",
  "confirmedBlockHeight": 1,
  "startBlockHeight": 5,
  "numTickets": 2,
  "decayConst": 1000,
  "feePercentage": 3,
  "endBlockHeight": 10,
  "startPrice": 50.00000000,
  "auctionPrice": 49.97501249,
  "txid": "5321e588da5c3a074c862c268f728efe764e1498a6d3f280538cc3deb4c26f31",
  "bids": [
    {
      "txid": "9e05949d53f2a0abcf29ffe40638f06a819d692fcdc4b3dc1f52fef316a933fb",
      "feePubKey": "026a04ab98d9e4774ad806e302dddeb63bea16b5cb5f223ee77478e861bb583eb3"
    }
  ]
}
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `target/debug/examples/demo`
[2019-05-22T12:05:24Z INFO  coordinator::coordinator] Running coordinator!
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MongoDb(OperationError("No servers available for the provided ReadPreference."))', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:312
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: futures::task_impl::core::get_ptr
             at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libcore/macros.rs:17
   9: <core::result::Result<T, E>>::unwrap
             at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libcore/result.rs:798
  10: demo::main
             at examples/demo.rs:79
  11: std::rt::lang_start::{{closure}}
             at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  13: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:87
  14: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: std::rt::lang_start
             at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libstd/rt.rs:64
  16: demo::guardnode

**Comment by nkostoulas** [comment]
db missing - resolved
