### ISSUE TITLE
scripts: automate service request creation

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/coordinator#23]
We need to extend the script in https://commerceblock.readthedocs.io/en/latest/request-guide/index.html and make it more automated. Add this script to `/scripts` and update the docs.

- [x] The script should check if there is an active request for the given genesis hash and if there is then it should exit.

- [x] The script should take inputs "request_duration" and "auction_duration". Given these and the current block count, start_height and end_height should be set accordingly.

- [x] Currently start price and decay const are supplied. It would be best to provide start price and end price and automatically calculate the decay const based on the formula used in Ocean.

- [x] The script should be able to read all input parameters from the command line so that we don't have to edit the script before running. If this is getting too complex it might be best to rewrite the script in Python. Check `scripts/report.py` on how to do RPC stuff in Python.

I think with the above changes we can set the script to run on a cronjob and it will automatically create a new request when the previous one ends.

**Comment by nkostoulas** [comment]
Let me know if you think something could be done better.

**Comment by tomossomot** [comment]
Changes made [here](https://github.com/commerceblock/coordinator/compare/createRequest_script) let me know what you think.

**Comment by nkostoulas** [comment]
Nice work! A few things:

We'll need `alias ocl="ocean-cli -rpcport=7043 -rpcuser=ocean -rpcpassword=oceanpass"` as default because usually this will be run along Docker and your docker-compose files don't use an ocean.conf file but all the config is given in the command line, thus `-datadir` will not work.

Can you double check the decay const calculation? From the code decayConst is only divided from the cubed parameter `return nStartPrice*(1 + t)/(1 + t + pow(t,3)/nDecayConst);`. I'm getting: 
```
decay = $4^3 / ( ( 1 + $4 ) * ( $2 / $3 - 1) )
```

Also you've removed `scripts/demo.sh` in your branch.

**Comment by nkostoulas** [comment]
Also maybe it is worth removing $8 and $9 as that would involve the user actually keeping track of this transaction and also changing the parameters from that script. It would be best to only set $1-$7 once and never touch it again. 

The script could automatically spend a previously locked transaction. With your last change in Ocean, locked utxos will showup in `listunspent` so you could basically pick the first result from this and if it is locked multisig then do the appropriate checks.

**Comment by tomossomot** [comment]
Okay fixed decay equation and included demo.sh.

I've left in the option for use to include funding transaction, but if not given the script grabs the first TX_LOCKED_MULTISIG that has a valid locktime and uses that.

**Comment by nkostoulas** [comment]
Cool looks good. Can you update the docs https://commerceblock.readthedocs.io/en/latest/request-guide/index.html with a link to this script once merged please.

**Comment by nkostoulas** [comment]
> I've left in the option for use to include funding transaction, but if not given the script grabs the first TX_LOCKED_MULTISIG that has a valid locktime and uses that.

It should still work even if you don't have any locked unspent.

**Comment by nkostoulas** [comment]
Sorry one more thing. Could you add an argument for a private key? That would be the key that holds the PERMISSION asset and the script will have to import this if not already imported. This way everything will be done automatically in production and we don't have to touch the node. I think there is a way to check if a key has already been imported (possibly by using `validateaddress` on the corresponding address and checking `ismine`) in order to avoid re-importing and re-scanning.

**Comment by nkostoulas** [comment]
rpcuser/rpcpass/rpcport/rpconnect need to be configurable also. You can use env variables, e.g.

`export RPC_CONNECT=localhost`

and read the env in the code, instead of happing a very long list of command line arguments.
