### ISSUE TITLE
storage: db indexes

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/coordinator#44]
It would be good to index the Request collection by "txid".

It would also be good to index Bid and Response collections by "request_id", which is the foreign key "_id" to the Request collection. Maybe this is already indexed or maybe it needs to be specified explicitly.

**Comment by tomossomot** [comment]
Bid and Response already indexed by "_id" but made explicit anyway.  

[PR](https://github.com/commerceblock/coordinator/pull/46)

**Comment by nkostoulas** [comment]
I meant Request's "request_id" but I think you covered that.
