### ISSUE TITLE
challenger: incorrect end_blockheight_clientchain

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/coordinator#52]
This is set to the height **after** the end of the service period. It should be set to the height at that point subtracting the different between service end and current service height.

```
if (request.end_blockheight as u64) < challenge_height {
            request.end_blockheight_clientchain = clientchain.get_block_count()? - (challenge_height - request.end_blockheight);
            storage.update_request(request)?;
            break;
        } 
```

The unit-test should also reflect this.

This is not 100% accurate and assumes that service chain and client chain have the same block time, but what to do.

**Comment by tomossomot** [comment]
Change so that `end_blockheight_clientchain` is calculated at the same time that `start_blockheight_clientchain` is set. This is done by adding a `block_time` field to client and service chain config and working out expected number of client chain blocks passed in time  
(`end_blockheight` - `start_blockheight`)*`block_time_servicechain`

Move relevant code into seperate function and perform unit tests. Have a look into mongo mock storage capabilities for this also.

**Comment by nkostoulas** [comment]
@tomossomot take this code segment 
```
            match storage.get_request(challenge.request.txid)? {
                Some(req) => challenge.request = req,
                None => {
                    // Set request's start_blockheight_clientchain
                    challenge.request.start_blockheight_clientchain = clientchain.get_block_count()?;
                    // Store Challenge Request
                    storage.save_challenge_state(&challenge)?;
                }
            }
```
along with any additional stuff you add for this issue and put them in a separate function so that it can be unit-tested in `coordinator.rs`. It's hard to test `run_request` but this code part is the only one with "real" logic so until we do a proper integration test this should be enough.

**Comment by nkostoulas** [comment]
Or maybe add this function (say `update_challenge_request_state`) in `challenger` if you think its more relevant. The test should check that given the heights are set correctly, it's correctly stored once and if run again the request is updated from the value in storage.

**Comment by tomossomot** [comment]
Update docs before closing issue

**Comment by tomossomot** [comment]
CO_CHALLENGE_FREQUENCY and CO_CHALLENGE_DURATION are listed in docs as env variable configurables but there is no code to pick them up. Is this intentional?

**Comment by nkostoulas** [comment]
Envs from base `Config` struct are picked automatically by `CO_<field_name>` if you see `.merge(Environment::with_prefix("CO"))?;`. Unfortunately the same dose not apply for child structs due to some library issue #4, so I've had to do it manually for now.

**Comment by tomossomot** [comment]
I see. 

docs up to date then.
